//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalStructureSearchingDemo.SearcherWebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemicalStructureSearchingDemo.SearcherWebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SMMXDraw01031111172D
        ///
        ///  4  3  0  0  0  0  0  0  0  0999 V2000
        ///   14.2188   -8.7813    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   14.9348   -8.3679    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   14.9348   -7.5411    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   15.6508   -8.7813    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0  0  0  0
        ///  2  3  2  0  0  0  0
        ///  2  4  1  0  0  0  0
        ///M  END
        ///.
        /// </summary>
        internal static string acid_chloride {
            get {
                return ResourceManager.GetString("acid_chloride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -ISIS-  12170917212D
        ///
        /// 25 27  0  0  0  0  0  0  0  0999 V2000
        ///    3.1187   -3.6583    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.4042   -4.0708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.4042   -4.8958    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.1187   -5.3083    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8332   -4.8958    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8332   -4.0708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.6911   -4.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ampicillin {
            get {
                return ResourceManager.GetString("ampicillin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Marvin  01211005432D          
        ///
        /// 22 23  0  0  0  0            999 V2000
        ///   -1.8707    0.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.8707   -0.7250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.1562   -1.1375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4418   -0.7250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4418    0.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.1562    0.5125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prozac {
            get {
                return ResourceManager.GetString("Prozac", resourceCulture);
            }
        }
    }
}
